Created the separate function to add comments
Space2Study-UA-1156/BackEnd-01 pull request #51
Opened 2024-04-25 09:15 UTC by holus-bolus

Changed the function structure accordingly to requirements

![image](https://github.com/Space2Study-UA-1156/BackEnd-01/assets/93076661/3a3a2be4-a8fb-4bcd-93c8-7413e901fc35)

now when we create the comment, it has the required structure

![image](https://github.com/Space2Study-UA-1156/BackEnd-01/assets/93076661/d2d2be16-8213-45e7-95c5-76b951cd7716)

2024-04-25 16:31 UTC, YaroslavChuiko requested changes
it can help

2024-04-25 16:31 UTC, YaroslavChuiko commented on src/services/comment.js
> +    })
```suggestion
const comment = await Comment.create({ author, text, cooperation: cooperationId, authorRole })
```

2024-04-25 16:31 UTC, YaroslavChuiko commented on src/services/comment.js
> +    return result
```suggestion
    return await Comment.findById(comment._id).select('-authorRole').populate({
      path: 'author',
      select: 'firstName lastName'
    })
```

2024-04-25 16:31 UTC, YaroslavChuiko commented on src/services/comment.js
> +    return await Comment.find({ cooperation: cooperationId }).populate({
```suggestion
    return await Comment.find({ cooperation: cooperationId }).select('-authorRole').populate({
```

2024-04-25 18:04 UTC, holus-bolus commented on src/services/comment.js
> +    return await Comment.find({ cooperation: cooperationId }).populate({
Correcrted accordingly to suggestions

2024-04-25 18:19 UTC, YaroslavChuiko approved these changes

2024-04-26 14:09 UTC, OlhaOvsiienko approved these changes

2024-04-30 08:30 UTC, voloshkin-v approved these changes

2024-05-01 07:06 UTC, vlad-khrychov approved these changes

2024-05-01 07:21 UTC, merged